In [57]:
import numpy as np
import random

Question 1

In [58]:
arr = np.array([[1, 2], [3, 4]])

print(arr)

[[1 2]
 [3 4]]


Question 2

In [59]:
random_array = np.random.rand(3,4)

print(random_array)

[[0.94635633 0.36877552 0.71694943 0.45106446]
 [0.83343299 0.57249461 0.00502076 0.89628038]
 [0.32834535 0.49501949 0.47696735 0.14447611]]


Question 3


In [60]:
array_of_ones = np.ones((3, 3))
print("The array of ones is: ")
print(array_of_ones)

array_of_zeroes = np.zeros((3, 3))
print("The array of zeroes is: ")
print(array_of_zeroes)

The array of ones is: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
The array of zeroes is: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Question 4

In [61]:
random_array_big = np.random.randint(low = 0, high = 100, size = (6, 3))
print("Original array is: \n", random_array_big)

arr_tranposed = random_array_big.T  # .T means tranpose, commonly used in 2D array
print("\nTranposed array is: \n", arr_tranposed)


Original array is: 
 [[62 63 20]
 [24 94 71]
 [89  4 72]
 [88 11 34]
 [47 28 38]
 [39 15 97]]

Tranposed array is: 
 [[62 24 89 88 47 39]
 [63 94  4 11 28 15]
 [20 71 72 34 38 97]]


Question 5

In [62]:
print("Create two random numpy array of size n x p and p x m and then compute the dot product")
n = int(input("Enter the n: "))
p = int(input("Enter the p: "))
m = int(input("Enter the m: "))
print(" ")

array1 = np.random.randint(low = 0 , high = 100, size = (n, p))
print("array1 is: \n", array1)
print("\n")

array2 = np.random.randint(low = 0 , high = 100, size = (p, m))
print("array2 is: \n", array2)
print("\n")

dot_product = np.dot(array1, array2)
print("The dot product is: \n", dot_product)

Create two random numpy array of size n x p and p x m and then compute the dot product
Enter the n: 2
Enter the p: 3
Enter the m: 2
 
array1 is: 
 [[58 81 10]
 [49 74  0]]


array2 is: 
 [[ 4 87]
 [28 11]
 [56 61]]


The dot product is: 
 [[3060 6547]
 [2268 5077]]
